### ISSUE TITLE
FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by SvennoNito** [perrette/papers#14]
When I call `python scripts\papers extract esd-4-11-2013.pdf` in the anaconda prompt, also as an administrator, I get this error:

```
(PaperDownload) (base) C:\phd_scripts\paper-download\papers-master>python scripts\papers extract esd-4-11-2013.pdf
Traceback (most recent call last):
  File "scripts\papers", line 5, in <module>
    papers.bib.main()
  File "C:\ProgramData\Anaconda3\lib\site-packages\papers\bib.py", line 1359, in main
    extractcmd(o)
  File "C:\ProgramData\Anaconda3\lib\site-packages\papers\bib.py", line 1284, in extractcmd
    print(extract_pdf_metadata(o.pdf, search_doi=not o.fulltext, search_fulltext=True, scholar=o.scholar, minwords=o.word_count, max_query_words=o.word_count))
  File "C:\ProgramData\Anaconda3\lib\site-packages\papers\extract.py", line 201, in extract_pdf_metadata
    txt = pdfhead(pdf, maxpages, minwords, image=image)
  File "C:\ProgramData\Anaconda3\lib\site-packages\papers\extract.py", line 138, in pdfhead
    txt += readpdf(pdf, first=i, last=i)
  File "C:\ProgramData\Anaconda3\lib\site-packages\papers\extract.py", line 37, in readpdf
    sp.check_call(cmd)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 342, in check_call
    retcode = call(*popenargs, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 323, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 775, in __init__
    restore_signals, start_new_session)
  File "C:\ProgramData\Anaconda3\lib\subprocess.py", line 1178, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
```

I'm on Windows 10, 64bit

**Comment by perrette** [comment]
Just to be sure, can you check that:
- esd-4-11-2013.pdf  is actually present 
- papers was installed correctly (via python setup.py install, see README)
