### ISSUE TITLE
Strange behavior with pdf-folder and bibtex folder

### ISSUE THREAD

**Issue by VolkovIlia** [perrette/papers#22]
my config:
```
{
  "bibtex": "/home/user/Library/Bibtex/lib.bib",
  "filesdir": "/home/user/Library/PDFs",
  "git": true,
  "gitdir": "/home/user/Library"
}
```
If I trying to use `paper add file.pdf` I got error:
```python
Traceback (most recent call last):
  File "/usr/bin/papers", line 5, in <module>
    papers.bib.main()
  File "/usr/lib/python3.9/site-packages/papers/bib.py", line 1350, in main
    check_install() and addcmd(o)
  File "/usr/lib/python3.9/site-packages/papers/bib.py", line 987, in addcmd
    savebib(my, o)
  File "/usr/lib/python3.9/site-packages/papers/bib.py", line 898, in savebib
    config.gitcommit()
  File "/usr/lib/python3.9/site-packages/papers/config.py", line 115, in gitcommit
    if not os.path.samefile(self.bibtex, target):
  File "/usr/lib/python3.9/genericpath.py", line 101, in samefile
    s2 = os.stat(f2)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Library/lib.bib'
```
But bib file is located `/home/user/Library/Bibtex/lib.bib`
If I add sim-link from `/home/user/Library/Bibtex/lib.bib -> /home/user/Library/lib.bib`
it works fine.

**Comment by perrette** [comment]
Hi, what does `papers status -v` says?
Closing for now. Please re-open if still relevant.
